set -g mouse on
set -g status-interval 5
set -g status-justify left
set -g status-position bottom
set -g automatic-rename off

set -g status-style "bg=#101010,fg=#fafafa"
set -g status-left ""
set -g status-left-length 0

set -g window-status-separator "  "
set -g window-status-current-format "#[fg=#fafafa,bg=#7a5200,bold]  #I #[fg=#101010,bg=#ffae00,bold] #{b:pane_current_path} "
set -g window-status-format "#[fg=#a8a8a8,bg=#1a1a1a]  #I #[fg=#fafafa,bg=#3a3a3a] #{b:pane_current_path} "

set -g status-right-length 250
set -g status-right "#[fg=#fafafa,bg=#003d80,bold]  #[fg=#101010,bg=#006aff,bold] #(basename $SHELL)  #[fg=#fafafa,bg=#7a5200,bold]  #[fg=#101010,bg=#ffae00,bold] #(~/.config/tmux/scripts/cpu.sh)  #[fg=#fafafa,bg=#155226,bold]  #[fg=#101010,bg=#29a948,bold] #{session_windows}  #[fg=#fafafa,bg=#00584d,bold]  #[fg=#101010,bg=#00ac96,bold] #(~/.config/tmux/scripts/uptime.sh)  #[fg=#fafafa,bg=#2a5f80,bold]  #[fg=#101010,bg=#49aeff,bold] #(~/.config/tmux/scripts/battery.sh)  "

set -g pane-border-style "fg=#a8a8a8"
set -g pane-active-border-style "fg=#006aff"

set -g message-style "bg=#ffae00,fg=#101010,bold"
set -g message-command-style "bg=#101010,fg=#fafafa"
set -g mode-style "bg=#005be7,fg=#fafafa"
