# Set prefix key as Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Allow mouse on
set -g mouse on

# Allow for VI keybindings for movement
setw -g mode-keys vi

# Set history to be loonnnggggg
set -g history-limit 50000

# Increase tmux message display duration from 750ms to 4sec
set -g display-time 4000

# When you press Enter after a selection, before releasing the mouse, it'll copy your select to the clipboard buffer
set-option -g set-clipboard external
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Allows for faster key repetition
set -s escape-time 0

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Set aggressive resize on
setw -g aggressive-resize on

# Pane navigation: Ctrl+Alt(Option)+Arrow keys (This is my config in Ghostty, so it's easier for me to manage)
bind -n C-M-Left  select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up    select-pane -U
bind -n C-M-Down  select-pane -D

# Pane resizing: Alt(Option)+Shift+Arrow keys
bind -n M-S-Left  resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up    resize-pane -U 3
bind -n M-S-Down  resize-pane -D 3

# Window navigation: Make it easier to switch between windows
bind C-p previous-window
bind C-n next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set theme
source-file ~/.config/tmux/themes/vercel.conf
# This theme is inspired by Ghostty's Vercel theme


# Set plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Save nvim session
set -g @resurrect-strategy-nvim 'session'

# Initialize TPM (keep at last of this file)
run '~/.tmux/plugins/tpm/tpm'
